name: CI Pipeline

on: push

jobs: 
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pipeline
        env:
          DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
        run: |
          dvc repro


  model-testing:
    needs: project-testing
    runs-on: ubuntu-latest

    steps: 
        - name: Run Test
          env:  
            DAGSHUB_PAT: ${{secrets.DAGSHUB_PAT}}
          run: |
            python -m unittest test/test_model.py

